version: '3'

services:
  db:
    container_name: db
    image: mysql:latest
    restart: always
    volumes:
      - ./db/dump:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - minharede

  app1:
    container_name: app1
    build:
      context: ./node
      dockerfile: Dockerfile
    restart: always
    tty: true
    volumes:
      - ./node:/app
    depends_on:
      - db
    command: >
      bash -c "npm i
      && chmod 777 wait-for-it.sh
      && ./wait-for-it.sh db:3306 --timeout=20 -- node index.js "
    networks:
      - minharede

  app2:
    container_name: app2
    build:
      context: ./node
      dockerfile: Dockerfile
    restart: always
    tty: true
    volumes:
      - ./node:/app
    depends_on:
      - db
    command: >
      bash -c "npm i
      && chmod 777 wait-for-it.sh
      && ./wait-for-it.sh db:3306 --timeout=20 -- node index.js "
    networks:
      - minharede

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - app1
      - app2
    networks:
      - minharede

networks:
  minharede:
    driver: bridge